In [3]:
import numpy as np

a= np.array([[3,7,5,6],[2,2,2,2]])
b=np.array([[1,2,3,4],[3,3,3,3]])
a2= a**2
distance=np.linalg.norm(a-b)
distance1= np.sqrt(np.sum((a-b)**2))
print(a,'a squre:',a2)
suma2=np.sum(a2)
print('sum a2',suma2)
print('test distance:', distance, distance1)

[[3 7 5 6]
 [2 2 2 2]] a squre: [[ 9 49 25 36]
 [ 4  4  4  4]]
sum a2 135
test distance: 6.4031242374328485 6.4031242374328485


In [2]:
t=np.argsort(a)
# inpus: t se luu gia tri cua index da sort
# returns: tra ve array tuong ung vs index da sort o a
#c=a[t[0]]
print (t)

[row,col]= t.shape
print (row,col)


[[0 2 3 1]
 [0 1 2 3]]
2 4


In [3]:
c=np.array([[1,2,3,4],[3,3,3,3],[5,5,5,5]])
a[0,:]-c

array([[ 2,  5,  2,  2],
       [ 0,  4,  2,  3],
       [-2,  2,  0,  1]])

In [4]:
print(c.shape, a.shape)
test=np.dot(c,a.T)
print(test)
print(test**2)
np.sum(c,axis=1)


(3, 4) (2, 4)
[[ 56  20]
 [ 63  24]
 [105  40]]
[[ 3136   400]
 [ 3969   576]
 [11025  1600]]


array([10, 12, 20])

In [5]:
print(c)
print(c[:,np.newaxis])
print (c.shape)
print (c[:,np.newaxis].shape)


[[1 2 3 4]
 [3 3 3 3]
 [5 5 5 5]]
[[[1 2 3 4]]

 [[3 3 3 3]]

 [[5 5 5 5]]]
(3, 4)
(3, 1, 4)


In [6]:
testx=a[0]
testy=np.array([5,1,5,5,5])
print (testx,testy)
testx=np.reshape(testx, (-1, 1))
testy=np.reshape(testy, (1, -1))
print(testx.shape)
print(testy.shape)
print('hihi:',testx+testy)
testx[:,np.newaxis]+testy

[3 7 5 6] [5 1 5 5 5]
(4, 1)
(1, 5)
hihi: [[ 8  4  8  8  8]
 [12  8 12 12 12]
 [10  6 10 10 10]
 [11  7 11 11 11]]


array([[[ 8,  4,  8,  8,  8]],

       [[12,  8, 12, 12, 12]],

       [[10,  6, 10, 10, 10]],

       [[11,  7, 11, 11, 11]]])

In [7]:
print (a)
t=np.split(a,2)
print (type (t))
print (type(a))
t[1]
# merge list
merge_list=[]
merge_list += [l for l in t]
print (merge_list)

[[3 7 5 6]
 [2 2 2 2]]
<class 'list'>
<class 'numpy.ndarray'>
[array([[3, 7, 5, 6]]), array([[2, 2, 2, 2]])]


In [8]:
lists = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

merged_list= np.concatenate([lists[i] for i in range (len(lists))])
# merged_list+= [item for l in lists for item in l]
# for l in lists:
#     print ('L:',l)
#     merged_list =merged_list+ l
#     print(merged_list)

print(merged_list)
print (type(merged_list))
print ('length', len(merged_list))
test= np.zeros((3,2))
print(test.shape[1])

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
length 9
2


In [24]:
#If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.
print (a)
print ('ashape: ',a.shape)
b= np.array ([1,2])
#b=np.reshape(b,(1,-1))
print ('b shape:',b.shape)
# a.dot(b) # cannot do, last axis of a =4, last axis of b=2
b.dot(a) # do the first axis of a and first axis ofb

[[3 7 5 6]
 [2 2 2 2]]
ashape:  (2, 4)
b shape: (2,)


array([ 7, 11,  9, 10])

In [32]:
a=np.array([1,2,3])
b=np.array ([1,2])
print (a.shape)
print(a[1,:])

(3,)


IndexError: too many indices for array

In [33]:
matrix = np.array([[1, 2, 3],[0, 3, 5],[1, 4, 4]])
vector = np.array([[1], [0], [2]])
print (matrix.shape, vector.shape)
np.choose(vector.flat, matrix.T)

(3, 3) (3, 1)


array([2, 0, 4])

In [44]:
#broadcasting
a = np.array([[1, 2, 3],[0, 3, 5],[1, 4, 4],[1,2,3]])
b = np.array([1,1,1])

print (a.shape, b.shape)
print (a-b)

(4, 3) (3,)
[[ 0  1  2]
 [-1  2  4]
 [ 0  3  3]
 [ 0  1  2]]


## SVM exercise

In [110]:
# Set some value in array a =0, which index store in matrix b.
#https://stackoverflow.com/questions/23435782/numpy-selecting-specific-column-index-per-row-by-using-a-list-of-indexes/23435843
# a= 4x3, b= 3
a = np.array([[1, 2, 3],[0, 3, 5],[1, 4, 4],[1,2,3]])
print ('a original:',a)
b = np.array([1,2,1,0])
print ('b original:',b)
margins=a
margins[np.arange(a.shape[0]),b]=0 # xét trên từng hàng của margins, cột của margins= giá trí tại cột tương ứng vs hàng a của b, set =0. Ví dụ: hàng 1 của margins, thì lấy giá trị ở cột 1 của b làm giá trị cột của margins
#margins[:,b]=0# xet tren tat ca cac hang cua margins, tất cả vị trí mà có trong giá trị của b, se set = 0 het
margins


a original: [[1 2 3]
 [0 3 5]
 [1 4 4]
 [1 2 3]]
b original: [1 2 1 0]


array([[1, 0, 3],
       [0, 3, 0],
       [1, 0, 4],
       [0, 2, 3]])

In [66]:
a = np.arange(5)
np.put(a, [0, 2], [-44, -55])
a


array([-44,   1, -55,   3,   4])

dw=500x10, y= 500. Thay the cac gia tri ma dw[indexwewant, y[index we want]]= gia tri nao do. Dùng trong đoạn tính gradient vectorized của SVM
Explained vectorized gradient SVM: https://mlxai.github.io/2017/01/06/vectorized-implementation-of-svm-loss-and-gradient-update.html 
Remember: read comments, summ over C class not over m examples

In [92]:
y = np.array([1, 2,2,3])
index_we_want= np.array([0,2])
dw = np.zeros((4,3))
dw[index_we_want, y[index_we_want]] = 42
print (dw)

[[ 0. 42.  0.]
 [ 0.  0.  0.]
 [ 0.  0. 42.]
 [ 0.  0.  0.]]


In [95]:
# Convert 2D array into 1D array
a = np.array([[1,2], [3,4]])
b=a.flatten()
print (a.shape)
print (b.shape)



(2, 2)
(4,)


In [106]:
t=a.shape
t= t+(3,)
new= np.zeros (t)
new


array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [109]:
a=np.array([[1,2],[1,1],[1,1]])
print(a.shape)
t= np.sum(a,axis=0)
t


(3, 2)


array([3, 4])

Linear Classifier - SGD


1.Create a Batch size from all training sample

In [116]:
a=np.array([[1,2,3],[1,1,1]])
b=np.array([1,0])
t= a[b,:]
t


array([[1, 1, 1],
       [1, 2, 3]])

###### SOftmax
https://mlxai.github.io/2017/01/09/implementing-softmax-classifier-with-vectorized-operations.html

numerical stability: http://cs231n.github.io/linear-classify/#softmax

Gradient computing: http://cs231n.github.io/neural-networks-case-study/#grad

Mathematical derivation: https://math.stackexchange.com/a/945918/359714

summary softmax gradient final results: https://mlxai.github.io/2017/01/09/implementing-softmax-classifier-with-vectorized-operations.html
Lúc làm nên tính trước loss và gradient để biết nhửng biến trung gian cần xài là gì

TÍnh gradient theo batch size: chính là lấy gradient, loss trên 1 tập data. Cộng dồn trên từng data, rồi chia ra trung bình theo số lượng batch 

In [4]:
# Exponential
np.exp(3)

20.085536923187668

In [27]:
# Minus each rows of matrix a with corresponding values in matrix B
# Used in the numerical stable in softmax loss
import numpy as np
a=np.array ([[2,2],[3,3],[2,2]])
b=np.array([3,1,1])
b=b[:, np.newaxis]
print (b.shape)
a-b

(3, 1)


array([[-1, -1],
       [ 2,  2],
       [ 1,  1]])

In [17]:
#Divide a for correspinding value in b. In softmax vectorized
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9],[2,2,2]]) 
b= np.array ([1,2,3,4])
c= a.T/b
c


array([[1.        , 2.        , 2.33333333, 0.5       ],
       [2.        , 2.5       , 2.66666667, 0.5       ],
       [3.        , 3.        , 3.        , 0.5       ]])

## 2 Layers Network

In [16]:
#a technique use, to keep the dimension when calculate softmax loss.
# Từng hàng của ma trận sẽ chia cho giá trị sum của mỗi hàng đó
# when use keep dims= true, the output of the axis loss by sum will set =0
#softmax_prob= exp_scores/ np.sum(exp_scores,axis=1, keepdims=True)#NxC
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9],[2,2,2]]) 
b= np.array ([[1,2,3,4],[0,0,0,0]])
b=b.T
# test= a/np.sum(b,axis=1)#operands could not be broadcast together with shapes (4,3) (4,). 
test= a/np.sum(b,axis=1,keepdims=True)  # 4x3 / 4x1 = 4
print ('keep dimension shape:',np.sum(b,axis=1,keepdims=True).shape)
print ('a shape:',a.shape)
print (test)

keep dimension shape: (4, 1)
a shape: (4, 3)
[[1.         2.         3.        ]
 [2.         2.5        3.        ]
 [2.33333333 2.66666667 3.        ]
 [0.5        0.5        0.5       ]]


# Image Feature


Thay vì train FC layers vào raw Image. Thì h dùng phương pháp thủ công tìm features , dựa trên features này rồi mới phân loại. Nên dạt kết quả tốt hơn. Sua này cải tiến thêm thì sẽ dùng end to end luôn. Tạo ra dc features tốt hơn.

Các cách trích xuất features: 1 dùng HOG để extract texture. Dùng H của HSV color, de extract color information. Rồi concate 2 features này (support code to do it)

Cách visualize results:
Visualize the loss, accuracy. Visualize the wrong classification, the raw image, which was classify wrong
